export const HELLO_REJECT_CODES = {
  UNSUPPORTED_PROFILE: 0x01,
  FILE_TOO_LARGE: 0x02,
  MEMORY_UNAVAILABLE: 0x03,
  INVALID_METADATA: 0x04,
  BUSY: 0x05
} as const;

export const FINAL_BAD_REASON_CODES = {
  MISSING_DATA_REMAINS: 0x01,
  FILE_LENGTH_MISMATCH: 0x02,
  WHOLE_FILE_CRC_MISMATCH: 0x03,
  INVALID_END_METADATA: 0x04
} as const;

export const CANCEL_REASON_CODES = {
  USER_CANCEL: 0x01,
  LOCAL_TIMEOUT: 0x02,
  UNRECOVERABLE_PROTOCOL_ERROR: 0x03
} as const;
